apiVersion: v1
kind: Pod
metadata:
  name: jedi
  namespace: kube-system
  labels:
    app: jedi
spec:
  volumes:
  - name: kadm-storage
    hostPath:
      path: /opt
  - name: dkreg-storage
    hostPath:
      path: /opt/dkreg
  containers:
  - name: kadm
    image: localhost/alp.kadm
    imagePullPolicy: Never
    ports:
    - containerPort: 22100
      hostPort: 22100
    volumeMounts:
    - name: kadm-storage
      mountPath: /opt
    securityContext:
      privileged: true
  - image: registry:2
    name: dkreg
    ports:
    - containerPort: 5000
      hostPort: 5000
    volumeMounts:
    - mountPath: "/var/lib/registry"
      name: dkreg-storage
    env:
    - name: REGISTRY_AUTH
      value: "htpasswd"
    - name: REGISTRY_AUTH_HTPASSWD_PATH
      value: "/var/lib/registry/htpasswd"
    - name: REGISTRY_AUTH_HTPASSWD_REALM
      value: "Registry Realm"
