apiVersion: v1
kind: Namespace
metadata:
  name: llm-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ollama
  name: ollama
  namespace: llm-system
spec:
  clusterIP: None
  ports:
  - port: 11434
    protocol: TCP
  selector:
    app: ollama
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webui
  name: webui
  namespace: llm-system
spec:
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 8080
  selector:
    app: webui
#  type: NodePort
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webui
  namespace: llm-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webui
  name: webui
  namespace: llm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - command:
        - bash
        - -c
        - |
          until ls ${SQLITE_DB} &>/dev/null; do
            sleep 3
          done
          sleep 3
          adduser.sh ${ADMIN_MAIL} ${ADMIN_PASSWORD} admin
          sleep infinity
        env:
        - name: ADMIN_MAIL
          value: admin@tks.com
        - name: ADMIN_PASSWORD
          value: admin
        - name: SQLITE_DB
          value: /app/backend/data/webui.db
        image: quay.io/flysangel/open-webui:dbadm-v1.0.0
        imagePullPolicy: Always
        name: dbadm
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /app/backend/data
          name: webui
      - env:
        - name: WEBUI_AUTH
          value: "True"
        - name: ENABLE_SIGNUP
          value: "False"
        - name: OLLAMA_BASE_URL
          value: http://ollama-0.ollama:11434
        - name: DEFAULT_MODELS
          value: llama3.2:1b
        - name: TASK_MODEL
          value: llama3.2:1b
        - name: RAG_EMBEDDING_ENGINE
          value: ollama
        - name: RAG_EMBEDDING_MODEL
          value: nomic-embed-text
        - name: ENABLE_OPENAI_API
          value: "False"
        image: ghcr.io/open-webui/open-webui:main
        imagePullPolicy: Always
        name: webui
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
        - mountPath: /app/backend/data
          name: webui
      hostname: webui
      restartPolicy: Always
      volumes:
      - name: webui
        persistentVolumeClaim:
          claimName: webui
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ollama
  name: ollama
  namespace: llm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  serviceName: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - image: quay.io/flysangel/ollama/ollama:latest
        imagePullPolicy: Always
        name: ollama
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
        - mountPath: /root/.ollama
          name: ollama
      initContainers:
      - command:
        - bash
        - -c
        - |
          ollama serve &
          sleep 5 # wait ollama server
          for model in echo $(echo ${PULL_MODELS} | tr ',' ' '); do
            ollama list | grep -q ${model} ||
              ollama pull ${model}
          done
        env:
        - name: PULL_MODELS
          value: llama3.2:1b,nomic-embed-text
        image: quay.io/flysangel/ollama/ollama:latest
        name: pull
        volumeMounts:
        - mountPath: /root/.ollama
          name: ollama
  volumeClaimTemplates:
  - metadata:
      name: ollama
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: local-path
