apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://bigred@kadm.kube-system:22100/home/bigred/gitops
    targetRevision: HEAD
    path: argo-workflows
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true