apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tke
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: ssh://bigred@kadm.kube-system:22100/home/bigred/gitops
        revision: HEAD
        directories:
          - path: tke/*
  template:
    metadata:
      name: "{{.path.basename}}"
    spec:
      project: "default"
      source:
        repoURL: ssh://bigred@kadm.kube-system:22100/home/bigred/gitops
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.path.basename}}"
      syncPolicy:
        # automated:
        #  allowEmpty: true
        #  prune: true
        #  selfHeal: true
      ignoreDifferences:
        - group: "apiextensions.k8s.io"
          kind: CustomResourceDefinition
          name: bgppeers.metallb.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
        - group: "apiextensions.k8s.io"
          kind: CustomResourceDefinition
          name: addresspools.metallb.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
