apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: s3-system
  name: minio-mgr
  labels:
    app: minio-mgr
spec:
  selector:
    matchLabels:
      app: minio-mgr # has to match .spec.template.metadata.labels
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: minio-mgr # has to match .spec.selector.matchLabels
    spec:
      hostname: minio-mgr
      containers:
        - name: minio-mgr
          image: quay.io/flysangel/image:alpine.s3cli-v1.0.0
          imagePullPolicy: Always # Always, Nerver, IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "256m"
            limits:
              memory: "512Mi"
              cpu: "512m"
