version: "3"

set: [errexit, nounset, pipefail]

tasks:
  install:
    desc: Install Argo CD CLI
    silent: true
    cmds:
      - bash "{{.ROOT_DIR}}/tools/argocd/install.sh"

  uninstall:
    desc: Uninstall Argo CD CLI
    silent: true
    cmds:
      - bash "{{.ROOT_DIR}}/tools/uninstall.sh" argocd
