apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-
spec:
  podGC:
    strategy: OnPodSuccess
  entrypoint: main

  templates:
    - name: main
      steps:
        - - name: git-checkout
            template: git-checkout    
        - - name: compile
            template: compile
            arguments:
              artifacts:
                - name: git-repo
                  from: "{{steps.git-checkout.outputs.artifacts.git-repo}}"
        - - name: test
            template: test
            arguments:
              artifacts:
                - name: compile-output
                  from: "{{steps.compile.outputs.artifacts.compile-output}}"
        - - name: build
            template: build
            arguments:
              artifacts:
                - name: compile-output
                  from: "{{steps.compile.outputs.artifacts.compile-output}}"
        - - name: deploy
            template: deploy
            arguments:
              artifacts:
                - name: compile-output
                  from: "{{steps.compile.outputs.artifacts.compile-output}}"

    - name: git-checkout
      inputs:
        artifacts:
          - name: goweb
            path: /workdir/goweb
            git:
              repo: ssh://bigred@kube-kadm.kube-system:22100/home/bigred/devops/goweb
              # insecureIgnoreHostKey disables SSH strict host key checking during the git clone
              insecureIgnoreHostKey: true
              # kubectl create secret generic git-cred --from-file=privateKey=/home/bigred/.ssh/id_rsa -n argo
              sshPrivateKeySecret:
                name: git-cred
                key: privateKey
      container:
        image: dkreg.kube-system:5000/alp.task:1.0.0-cicd
        command: [sh, -c]
        args: ["ls -al"]
        workingDir: /workdir/goweb
      outputs:
        artifacts:
          - name: git-repo
            path: /workdir/goweb

    - name: compile
      inputs:
        artifacts:
          - name: git-repo
            path: /workdir/goweb
      container:
        image: dkreg.kube-system:5000/alp.golang:1.0.0-cicd
        securityContext:
          privileged: true
        command: [sh, -c]
        args: ["task compile"]
        workingDir: /workdir/goweb
      outputs:
        artifacts:
          - name: compile-output
            path: /workdir/goweb

    - name: test
      inputs:
        artifacts:
          - name: compile-output
            path: /workdir/goweb
      retryStrategy:
        limit: "3"
      container:
        image: dkreg.kube-system:5000/alp.task:1.0.0-cicd
        command: [sh, -c]
        args: ["task run; sleep 2; task test"]
        workingDir: /workdir/goweb

    - name: build
      inputs:
        artifacts:
          - name: compile-output
            path: /workdir/goweb
      container:
        image: dkreg.kube-system:5000/alp.podman:1.0.0-cicd
        securityContext:
          privileged: true
        command: [sh, -c]
        args: ["task build"]
        workingDir: /workdir/goweb

    - name: deploy
      inputs:
        artifacts:
          - name: compile-output
            path: /workdir/goweb
      container:
        image: dkreg.kube-system:5000/alp.kubectl:1.0.0-cicd
        securityContext:
          privileged: true
        command: [sh, -c]
        args: ["task deploy"]
        workingDir: /workdir/goweb
