apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: minio-s3fs
  name: minio-s3fs
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: minio-s3fs
  template:
    metadata:
      labels:
        app: minio-s3fs
    spec:
      containers:
      - name: s3fs
        image: quay.io/cloudwalker/alp.mc.rclone.s3fs
        tty: true
        livenessProbe:           # 如果挂载点 /data 不可访问或 PVC 挂载失败，判定容器不健康
          exec:
            command:
            - ls
            - /opt/fbs
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/bash
                - -c
                - |
                  mkdir -p /opt/fbs
                  mkdir -p /opt/wp
                  sleep 10
                  echo 'minio:minio123' > /tmp/.passwd-s3fs
                  chmod 600 /tmp/.passwd-s3fs
                  echo 'user_allow_other' >> /etc/fuse.conf
                  s3fs wordpress /opt/wp -o allow_other -o passwd_file=/tmp/.passwd-s3fs -o url=http://minio.kube-system:9000 -o use_path_request_style -o dbglevel=info -o curldbg &>/dev/null &
                  s3fs fbs /opt/fbs -o allow_other -o passwd_file=/tmp/.passwd-s3fs -o url=http://minio.kube-system:9000 -o use_path_request_style -o dbglevel=info -o curldbg &>/dev/null &
          preStop:
            exec:
              command: 
                - /bin/bash"
                - -c
                - |
                  fusermount -u /opt/wp
                  rm -r /opt/wp
                  fusermount -u /opt/fbs
                  rm -r /opt/fbs

        securityContext:
          privileged: true
        volumeMounts:
        - name: s3fs    
          mountPath: /opt
          mountPropagation: Bidirectional
      volumes:
      - name: s3fs
        hostPath:
          path: /opt
