apiVersion: v1
kind: Service
metadata:
  name: miniomnmd
  namespace: kube-system
spec:
  allocateLoadBalancerNodePorts: false
  type: LoadBalancer
  loadBalancerIP: 172.22.1.149
#  type: ClusterIP
#  clusterIP: 10.98.0.100
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: mclient
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: mconsole
  selector:
    app: miniomnmd
