apiVersion: batch/v1
kind: Job
metadata:
  name: minio-job
  namespace: kube-system
spec:
  # If the field is set to 0, the Job will be eligible to be automatically deleted immediately 
  # after it finishes.
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      name: minio-job
    spec:
      containers:
      - name: minio-job
        image: quay.io/cloudwalker/alp.mc.rclone.s3fs
        tty: true
        command: ["sh", "-c"]
        args:
        - |
          sleep 60
          mc config host add tk8s http://minio.kube-system:9000 minio minio123
          mc admin config set tk8s storage_class standard=EC:1
          mc mb tk8s/fbs
          mc mb tk8s/wordpress
          sleep 30

      restartPolicy: Never
---
