apiVersion: batch/v1
kind: Job
metadata:
  name: jenkins-job-rmdir
  namespace: jenkins
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      nodeSelector:
        node: jenkins
      containers:
      - name: mkdir
        image: quay.io/flysangel/alpine:latest
        command: ["rm", "-rf", "/opt/jenkins"]
        volumeMounts:
          - mountPath: /opt
            name: opt
      volumes:
        - name: opt
          hostPath:
            path: /opt       
      restartPolicy: Never
  backoffLimit: 4
