apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: s3-system

resources:
- namespace.yaml
- miniosnsd.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: minio