apiVersion: v1
kind: Service
metadata:
  name: svc-derby
  annotations:
    metallb.universe.tf/address-pool: mlb-pool
spec:
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: dep-derby
  type: LoadBalancer  
