apiVersion: v1
kind: Pod
metadata:
  name: minio-0
  namespace: kube-system
  labels:
    app: miniomnmd
spec:
  hostname: minio-0
  subdomain: miniomnmd
  volumes:
  - name: minio-data0
    hostPath:
      path: /opt/m0data0
  - name: minio-data1
    hostPath:
      path: /opt/m0data1
  containers:
  - name: minio-0
    image: minio/minio
    volumeMounts:
    - name: minio-data0
      mountPath: /data0
    - name: minio-data1
      mountPath: /data1
    args:
    - server
    - --console-address
    - :9001 
    - http://minio-{0...1}.miniomnmd.kube-system.svc.k1.org/data{0...1} 
    env:
    - name: MINIO_ACCESS_KEY
      value: "minio"
    - name: MINIO_SECRET_KEY
      value: "minio123"
    ports:
    - containerPort: 9000
      name: mc
      protocol: TCP
    - containerPort: 9001
      name: mcweb
      protocol: TCP
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - miniomnmd
        topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Pod
metadata:
  name: minio-1
  namespace: kube-system
  labels:
    app: miniomnmd
spec:
  hostname: minio-1
  subdomain: minio
  volumes:
  - name: minio-data0
    hostPath:
      path: /opt/m1data0
  - name: minio-data1
    hostPath:
      path: /opt/m1data2
  containers:
  - name: minio-1    
    image: minio/minio
    volumeMounts:
    - name: minio-data0
      mountPath: /data0
    - name: minio-data1
      mountPath: /data1
    args:
    - server 
    - --console-address
    - :9001
    - http://minio-{0...1}.miniomnmd.kube-system.svc.k1.org/data{0...1}
    env:
    - name: MINIO_ACCESS_KEY
      value: "minio"
    - name: MINIO_SECRET_KEY
      value: "minio123"
    ports:
    - containerPort: 9000
      name: mc
      protocol: TCP
    - containerPort: 9001
      name: mcweb
      protocol: TCP
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app 
            operator: In
            values:
            - miniomnmd
        topologyKey: kubernetes.io/hostname
---
