version: "3"

set: [errexit, nounset, pipefail]

tasks:
  install:
    desc: Install krew
    silent: true
    cmds:
      - bash "{{.ROOT_DIR}}/tools/krew/install.sh"

  uninstall:
    desc: Uninstall krew
    silent: true
    cmds:
      - rm -rf -- ~/.krew