version: "3"

set: [errexit, nounset, pipefail]
silent: true

tasks:
  add-bash-completion:
    desc: Install bash-completion on Alpine Linux
    preconditions:
      - grep -q "Alpine" /etc/os-release
    cmds:
      - sudo apk update
      - sudo apk add bash-completion

  add-shellcheck:
    desc: Install shellcheck on Alpine Linux
    preconditions:
      - grep -q "Alpine" /etc/os-release
    cmds:
      - sudo apk update
      - sudo apk add shellcheck

  add-git:
    desc: Install git on Alpine Linux
    preconditions:
      - grep -q "Alpine" /etc/os-release
    cmds:
      - sudo apk update
      - sudo apk add git