apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
type: Opaque
stringData:
  # bcrypt hash of the admin password and its last modified time (required).
  # argocd account bcrypt --password Argo12345
  admin.password: "$2a$10$s8Pwu8r8KWQcO69TAU9NnOZoBiTUkr2pVrDJnFnc7D2j7Yo.N7iG2"
  # date +%FT%T%Z
  # admin.passwordMtime: "2024-08-24T17:51:28CST"