apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo

resources:
  - namespace.yaml
  - github.com/argoproj/argo-workflows/manifests/cluster-install?ref=v3.5.10
  - crb.yaml
  - mios-cred.yaml

patches:
  - path: wf-controller-cm.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: argo