apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
# mc config host add mios http://miniosnsd.s3-system:9000 minio minio123
# mc mb mios/workflows
# kubectl -n argo create secret generic minio-cred --from-literal=accesskey=minio --from-literal=secretkey=minio123
# archiveLogs will archive the main container logs as an artifact
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: workflows
      endpoint: miniosnsd.s3-system:9000
      insecure: true
      accessKeySecret:
        name: minio-cred
        key: accesskey
      secretKeySecret:
        name: minio-cred
        key: secretkey