apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wp
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 172.22.1.146
  allocateLoadBalancerNodePorts: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: wp
  labels:
    app: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: 172.22.1.11:5000/deb.wp:24.01
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        tty: true
        lifecycle:
          postStart:
            exec:
              command:
              - 'sh'
              - '-c'
              - |
                s3fs wordpress /var/www/html -o passwd_file=/tmp/.passwd-s3fs -o url=http://minio.kube-system:9000 -o use_path_request_style -o nonempty -o dbglevel=info -f -o curldbg &>/dev/null &
                sleep 10
                /usr/local/bin/docker-entrypoint.sh apache2-foreground
        ports:
        - containerPort: 80
          name: wp-pod-port
        env:
        - name: WORDPRESS_DB_HOST
          value: 'svc-mysqld.ndb.svc.k1.org'
        - name: WORDPRESS_DB_USER
          value: bigred
        - name: WORDPRESS_DB_PASSWORD
          value: bigred
        - name: WORDPRESS_DB_NAME
          value: wpdb
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          privileged: true
