apiVersion: batch/v1
kind: Job
metadata:
  name: job-dtp-bucket
  namespace: kube-system
spec:
  # If the field is set to 0, the Job will be eligible to be automatically deleted immediately after it finishes.
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      name: job-dtp-bucket
    spec:
      containers:
      - name: job-dtp-bucket
        image: quay.io/cloudwalker/alp.base:24.01
        tty: true
        command: ["sh", "-c"]
        args:
        - |
          mc config host add mios http://miniosnsd.kube-system:9000 minio minio123
          [ "$?" != "0" ] && echo "MinIO not exist" && exit 1

          wget https://dlcdn.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz -O /tmp/hadoop-3.3.6.tar.gz
          cd /tmp && tar xvfz hadoop-3.3.6.tar.gz

          wget https://dlcdn.apache.org/hive/hive-3.1.3/apache-hive-3.1.3-bin.tar.gz -O /tmp/apache-hive-3.1.3-bin.tar.gz
          cd /tmp && tar xvfz apache-hive-3.1.3-bin.tar.gz

          wget https://dlcdn.apache.org/spark/spark-3.4.3/spark-3.4.3-bin-hadoop3.tgz -O /tmp/spark-3.4.3-bin-hadoop3.tgz
          cd /tmp && tar xvfz spark-3.4.3-bin-hadoop3.tgz

          sshpass -p 'bigred' scp -o "StrictHostKeyChecking no" -P 22100 bigred@kube-kadm.kube-system:~/wulin/wkload/usdt/conf/hdp3.3/* /tmp/hadoop-3.3.6/etc/hadoop/
          sshpass -p 'bigred' scp -o "StrictHostKeyChecking no" -P 22100 bigred@kube-kadm.kube-system:~/wulin/wkload/usdt/bin/* /tmp/hadoop-3.3.6/bin/
          sshpass -p 'bigred' scp -o "StrictHostKeyChecking no" -P 22100 bigred@kube-kadm.kube-system:~/wulin/wkload/usdt/conf/hive3.1.3/* /tmp/apache-hive-3.1.3-bin/conf/
          sshpass -p 'bigred' scp -o "StrictHostKeyChecking no" -P 22100 bigred@kube-kadm.kube-system:~/wulin/wkload/usdt/conf/spark3.4.3/* /tmp/spark-3.4.3-bin-hadoop3/conf/

          mc rm -r --force mios/dtp/ && mc rb mios/dtp 
          mc mb mios/dtp

          mc mb mios/dtp/hdp3.3
          mc cp -r /tmp/hadoop-3.3.6/ mios/dtp/hdp3.3 

          mc mb mios/dtp/hive3.1.3 
          mc cp -r /tmp/apache-hive-3.1.3-bin/ mios/dtp/hive3.1.3

          mc mb mios/dtp/spark3.4.3
          mc cp -r /tmp/spark-3.4.3-bin-hadoop3/ mios/dtp/spark3.4.3

      restartPolicy: Never
