version: "3"

set: [errexit, nounset, pipefail]
silent: true

includes:
  argo: argo/Tasks.yaml
  argocd: argocd/Tasks.yaml
  krew: krew/Tasks.yaml
  kube-linter: kube-linter/Tasks.yaml
  kubectl-argo-rollouts: kubectl-argo-rollouts/Tasks.yaml
  kubectl: kubectl/Tasks.yaml
  kustomize: kustomize/Tasks.yaml
  mc: mc/Tasks.yaml
  talosctl: talosctl/Tasks.yaml
  alpine: alpine/Tasks.yaml

tasks:
  default:
    cmds:
      - task --taskfile Taskfile.yaml -l
    silent: true

  install-all:
    desc: Install All tools
    cmds:
      - task: argo:install
      - task: argocd:install
      - task: kube-linter:install
      - task: kubectl-argo-rollouts:install
      - task: kustomize:install
      # - task: kubectl:install
      # - task: mc:install
      # - task: talosctl:install

  uninstall-all:
    desc: Uninstall All tools
    cmds:
      - task: argo:uninstall
      - task: argocd:uninstall
      - task: kube-linter:uninstall
      - task: kubectl-argo-rollouts:uninstall
      - task: kustomize:uninstall
      # - task: kubectl:uninstall
      # - task: mc:uninstall
      # - task: talosctl:uninstall
