version: "3"

set: [errexit, nounset, pipefail]

tasks:
  install:
    desc: Install KubeLinter
    silent: true
    cmds:
      - bash "{{.ROOT_DIR}}/tools/kube-linter/install.sh"

  uninstall:
    desc: Uninstall KubeLinter
    silent: true
    cmds:
      - bash "{{.ROOT_DIR}}/tools/uninstall.sh" kube-linter

