version: "3"

set: [errexit, nounset, pipefail]

tasks:
  install:
    desc: Install talosctl
    silent: true
    cmds:
      - bash "{{.ROOT_DIR}}/tools/talosctl/install.sh"

  uninstall:
    desc: Uninstall talosctl
    silent: true
    cmds:
      - bash "{{.ROOT_DIR}}/tools/uninstall.sh" talosctl
