apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: s3-system

resources:
  - https://raw.githubusercontent.com/juicedata/juicefs-csi-driver/master/deploy/k8s.yaml
  - sc-juicefs.yaml

images:
  - name: juicedata/juicefs-csi-driver
    newName: quay.io/flysangel/juicedata/juicefs-csi-driver
  - name: juicedata/csi-dashboard
    newName: quay.io/flysangel/juicedata/csi-dashboard

patches:
  - target:
      kind: Deployment
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ignored
      spec:
        replicas: 1
  - target:
      kind: StatefulSet
    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: ignored
      spec:
        replicas: 1
