apiVersion: v1
kind: Secret
metadata:
  namespace: s3-system # Notice
  name: juicefs-minio-secret
type: Opaque
stringData:
  name: "data"
  metaurl: "redis://redis.s3-system.svc.k1.org/1" # Notice
  storage: "minio"
  bucket: "http://miniosnsd.s3-system.svc.k1.org:9000/juicefs" # Notice
  access-key: "minio"
  secret-key: "minio123"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs-minio
  annotations:
    argocd.argoproj.io/hook: PostSync
provisioner: csi.juicefs.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  csi.storage.k8s.io/node-publish-secret-name: juicefs-minio-secret
  csi.storage.k8s.io/node-publish-secret-namespace: s3-system # CSI Driver deploy on which namespace
  csi.storage.k8s.io/provisioner-secret-name: juicefs-minio-secret
  csi.storage.k8s.io/provisioner-secret-namespace: s3-system # CSI Driver deploy on which namespace
