version: "3"

set: [errexit, nounset, pipefail]

tasks:
  install:
    desc: Install Argo Rollouts Kubectl plugin
    silent: true
    cmds:
      - bash "{{.ROOT_DIR}}/tools/kubectl-argo-rollouts/install.sh"

  uninstall:
    desc: Uninstall Argo Rollouts Kubectl plugin
    silent: true
    cmds:
      - bash "{{.ROOT_DIR}}/tools/uninstall.sh" kubectl-argo-rollouts
