version: "3"

set: [errexit, nounset, pipefail]

tasks:
  default:
    silent: true
    cmds:
      - task -l

  login:
    desc: Login to a container registry
    silent: true
    cmds:
      - sudo podman login --tls-verify=false -u bigred -p bigred dkreg.kube-system:5000 &>/dev/null

  logout:
    desc: Logout of a container registry
    silent: true
    cmds:
      - sudo podman logout dkreg.kube-system:5000 &>/dev/null

  rmi-none:
    desc: Clear <none> tag images
    silent: true
    cmds:
      - sudo podman rmi $(sudo podman images -f "dangling=true" -q)

  catalog:
    desc: Get catalog from docker private registry
    silent: true
    cmds:
      - curl -s -u bigred:bigred -X GET http://dkreg.kube-system:5000/v2/_catalog | jq

  build-all:
    desc: Build devops required images
    silent: true
    cmds:
      - task: build-base
      - task: build-task
      - task: build-golang
      - task: build-hadolint
      - task: build-kube-linter
      - task: build-kubectl
      - task: build-podman
      - task: build-shellcheck
      - task: logout

  build-base:
    desc: Build alp.base image
    cmds:
      - vars:
          IMAGE_NAME: alp.base
          IMAGE_TAG: 1.0.0-cicd
        task: build-template

  build-golang:
    desc: Build alp.golang image
    cmds:
      - vars:
          IMAGE_NAME: alp.golang
          IMAGE_TAG: 1.0.0-cicd
        task: build-template

  build-hadolint:
    desc: Build alp.hadolint image
    cmds:
      - vars:
          IMAGE_NAME: alp.hadolint
          IMAGE_TAG: 1.0.0-cicd
        task: build-template

  build-kube-linter:
    desc: Build alp.kube-linter image
    cmds:
      - vars:
          IMAGE_NAME: alp.kube-linter
          IMAGE_TAG: 1.0.0-cicd
        task: build-template

  build-kubectl:
    desc: Build alp.kubectl image
    cmds:
      - vars:
          IMAGE_NAME: alp.kubectl
          IMAGE_TAG: 1.0.0-cicd
        task: build-template

  build-podman:
    desc: Build alp.podman image
    cmds:
      - vars:
          IMAGE_NAME: alp.podman
          IMAGE_TAG: 1.0.0-cicd
        task: build-template

  build-shellcheck:
    desc: Build alp.shellcheck image
    cmds:
      - vars:
          IMAGE_NAME: alp.shellcheck
          IMAGE_TAG: 1.0.0-cicd
        task: build-template

  build-task:
    desc: Build alp.task image
    cmds:
      - vars:
          IMAGE_NAME: alp.task
          IMAGE_TAG: 1.0.0-cicd
        task: build-template

  build-template:
    desc: Template for build and push image
    internal: true
    silent: true
    vars:
      FROM_VER: '{{ default "1.0.0-cicd" .FROM_VER }}'
      IMAGE: 'dkreg.kube-system:5000/{{.IMAGE_NAME}}:{{.IMAGE_TAG}}'
    requires:
      vars: [IMAGE_NAME,IMAGE_TAG]
    cmds:
      - task: login
      - >-
        sudo podman build
        --build-arg FROM_VER={{.FROM_VER}}
        --format=docker --no-cache --force-rm --squash-all --tls-verify=false
        -t {{.IMAGE}} ~/devops/images/{{.IMAGE_NAME}}/ &>/dev/null
        && echo "{{.IMAGE}} image ok"
      - sudo podman push --tls-verify=false {{.IMAGE}} &>/dev/null && echo "{{.IMAGE}} push ok"
