apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-mysql-s3fs
spec:
  selector:
    matchLabels:
      app: mysql-s3fs
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-s3fs
    spec:
      containers:
      - name: s3fs
        image: 172.22.1.11:5000/alp.base:24.01
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - name: mysql
          mountPath: /mysql
          mountPropagation: Bidirectional
        lifecycle:
          postStart:
            exec:
             command:
             - /bin/bash
             - -c
             - |
               echo 'minio:minio123' > /tmp/.passwd-s3fs; chmod 600 /tmp/.passwd-s3fs;
               s3fs mysql /mysql/  -o uid=999 -o gid=999 -o allow_other -o passwd_file=/tmp/.passwd-s3fs -o url=http://miniosnsd.kube-system:9000 -o use_path_request_style -o dbglevel=info -f -o curldbg &>/dev/null &
          preStop:
            exec:
             command:
             - /bin/bash
             - -c
             - |
               sleep 30
               umount /mysql
      - name: mysql
        image: 172.22.1.11:5000/oracle.mysql:24.01
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args: ["sleep 30; docker-entrypoint.sh mysqld"]
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql
        hostPath:
          path: /opt/mysql
          type: Directory
