apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx

resources:
  - github.com/kubernetes/ingress-nginx/deploy/static/provider/baremetal?ref=controller-v1.11.2

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: ingress-nginx