apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: c29

# https://kind.sigs.k8s.io/docs/user/configuration/#networking
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "172.20.0.148"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443

nodes:
- role: control-plane
  image: quay.io/flysangel/kindest/node:v1.29.2
  extraPortMappings:
  # kadm ssh
  - containerPort: 22001
    hostPort: 22001
    protocol: TCP
  # kadm-ui ssh
  - containerPort: 22002
    hostPort: 22002
    protocol: TCP
  # kadm-ui vnc
  - containerPort: 5900
    hostPort: 5900
    protocol: TCP
  - containerPort: 6080
    hostPort: 6080
    protocol: TCP
  # kubevirt vnc
  - containerPort: 5901
    hostPort: 5901
    protocol: TCP
  - containerPort: 5902
    hostPort: 5902
    protocol: TCP
  - containerPort: 5903
    hostPort: 5903
    protocol: TCP
  - containerPort: 5904
    hostPort: 5904
    protocol: TCP
  - containerPort: 5905
    hostPort: 5905
    protocol: TCP
  # wireguard vpn
  - containerPort: 51820
    hostPort: 51820
    protocol: UDP
- role: worker
  image: quay.io/flysangel/kindest/node:v1.29.2
  extraPortMappings:
  # remote
  - containerPort: 33891
    hostPort: 33891
    protocol: TCP
  - containerPort: 22011
    hostPort: 22011
    protocol: TCP
- role: worker
  image: quay.io/flysangel/kindest/node:v1.29.2
  extraPortMappings:
  # remote
  - containerPort: 33892
    hostPort: 33892
    protocol: TCP
  - containerPort: 22012
    hostPort: 22012
    protocol: TCP
    