apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: s3-system

resources:
  - pvc-redis.yaml
  - dep-redis.yaml
  - svc-redis.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: redis
