apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: kube-nadm
  name: kube-nadm
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kube-nadm
  template:
    metadata:
      labels:
        app: kube-nadm
    spec:
      containers:
      - name: nadm
        image: quay.io/cloudwalker/alp.kadm
        imagePullPolicy: Always
        ports:
        - containerPort: 22100
          hostPort: 22
        securityContext:
          privileged: true
        volumeMounts:
        - name: nopt    
          mountPath: /opt
          mountPropagation: Bidirectional
      volumes:
      - name: nopt
        hostPath:
          path: /opt
