#!/bin/bash
cred="jenkins:Jenkins12345"
validateURL="http://devops.jenkins/pipeline-model-converter/validate"
reponse=$(curl -s --user ${cred} -X POST -F "jenkinsfile=<Jenkinsfile" ${validateURL})
echo "$reponse"
if [ "Jenkinsfile successfully validated." == "$reponse" ]; then
  exit 0
else
  exit 1
fi