version: "3"

set: [errexit, nounset, pipefail]

tasks:
  install:
    desc: Install Kustomize
    silent: true
    cmds:
      - bash "{{.ROOT_DIR}}/tools/kustomize/install.sh"

  uninstall:
    desc: Uninstall Kustomize
    silent: true
    cmds:
      - bash "{{.ROOT_DIR}}/tools/uninstall.sh" kustomize
