version: "3"

set: [errexit, nounset, pipefail]

tasks:
  install:
    desc: Install MinIO Clinet
    silent: true
    cmds:
      - bash "{{.ROOT_DIR}}/tools/mc/install.sh"

  uninstall:
    desc: Uninstall MinIO Clinet
    silent: true
    cmds:
      - bash "{{.ROOT_DIR}}/tools/uninstall.sh" mc
