apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-fbs-minio
  labels:
    app: dep-fbs-minio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dep-fbs-minio
  template:
    metadata:
      labels:
        app: dep-fbs-minio
    spec:
      containers:
      - image: 172.22.1.11:5000/alp.fbs:24.01
        name: fbs-minio
        ports:
        - containerPort: 4000
        securityContext:
          privileged: true
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/bash
                - -c
                - |
                  echo minio:minio123 > /tmp/.passwd-s3fs; chmod 600 /tmp/.passwd-s3fs;
                  s3fs fbs /srv -o passwd_file=/tmp/.passwd-s3fs -o url=http://svc-mios.default:9000 -o use_path_request_style -o dbglevel=info -f -o curldbg &>/dev/null & 
