kind: Service
apiVersion: v1
metadata:
  name: svc-fbs-minio
  annotations:
    metallb.universe.tf/address-pool: mlb-pool
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  selector:
    app: dep-fbs-minio
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
