apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mywk-
spec:
  entrypoint: p1
  templates:
    - name: p1
      container:
        image: dkreg.kube-system:5000/alp.base:1.0.0-cicd
        command:
          - /bin/sh
          - -c
          - |
            whoami
            pwd
            ls -al
            cat /etc/os-release
            hostname
            hostname -i

    - name: p2
      container:
        image: dkreg.kube-system:5000/alp.base:1.0.0-cicd
        command:
          - /bin/sh
          - -c
          - |
            echo "Hello! P2"