apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-
spec:
  podGC:
    strategy: OnPodSuccess
  entrypoint: main

  templates:
    - name: main
      steps:
        - - name: git-checkout
            template: git-checkout    
        - - name: compile
            template: compile
            arguments:
              artifacts:
                - name: git-repo
                  from: "{{steps.git-checkout.outputs.artifacts.git-repo}}"

    - name: git-checkout
      inputs:
        artifacts:
          - name: goweb
            path: /workdir/goweb
            git:
              repo: ssh://bigred@kube-xadm.taroko:22102/home/bigred/wulin/argo/wk/goweb
              # insecureIgnoreHostKey disables SSH strict host key checking during the git clone
              insecureIgnoreHostKey: true
              # kubectl create secret generic git-cred --from-file=privateKey=/home/bigred/.ssh/id_rsa -n argo
              sshPrivateKeySecret:
                name: git-cred
                key: privateKey
      container:
        image: dkreg.taroko:5000/alp.task:1.0.0-cicd
        command: [sh, -c]
        args: ["ls -al"]
        workingDir: /workdir/goweb
      outputs:
        artifacts:
          - name: git-repo
            path: /workdir/goweb

    - name: compile
      inputs:
        artifacts:
          - name: git-repo
            path: /workdir/goweb
      container:
        image: dkreg.taroko:5000/alp.golang:1.0.0-cicd
        securityContext:
          privileged: true
        command: [sh, -c]
        args: ["task compile"]
        workingDir: /workdir/goweb
      outputs:
        artifacts:
          - name: compile-output
            path: /workdir/goweb
