apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-
spec:
  podGC:
    strategy: OnPodSuccess
  entrypoint: main

  templates:
    - name: main
      dag:
        tasks:
        - name: git-checkout
          template: git-checkout
        - name: shellcheck
          dependencies: [git-checkout]
          template: shellcheck
          arguments:
            artifacts:
              - name: git-repo
                from: "{{tasks.git-checkout.outputs.artifacts.git-repo}}"
        - name: hadolint
          dependencies: [git-checkout]
          template: hadolint
          arguments:
            artifacts:
              - name: git-repo
                from: "{{tasks.git-checkout.outputs.artifacts.git-repo}}"
        - name: compile
          dependencies: [shellcheck, hadolint]
          template: compile
          arguments:
            artifacts:
              - name: git-repo
                from: "{{tasks.git-checkout.outputs.artifacts.git-repo}}"
        - name: test
          dependencies: [compile]
          template: test
          arguments:
            artifacts:
              - name: compile-output
                from: "{{tasks.compile.outputs.artifacts.compile-output}}"
        - name: build
          dependencies: [test]
          template: build
          arguments:
            artifacts:
              - name: compile-output
                from: "{{tasks.compile.outputs.artifacts.compile-output}}"
        - name: deploy
          dependencies: [build]
          template: deploy
          arguments:
            artifacts:
              - name: compile-output
                from: "{{tasks.compile.outputs.artifacts.compile-output}}"

    - name: git-checkout
      inputs:
        artifacts:
          - name: goweb
            path: /workdir/goweb
            git:
              repo: ssh://bigred@kadm.kube-system:22100/home/bigred/wulin/devops/goweb
              # insecureIgnoreHostKey disables SSH strict host key checking during the git clone
              insecureIgnoreHostKey: true
              # kubectl create secret generic git-cred --from-file=privateKey=/home/bigred/.ssh/id_rsa -n argo
              sshPrivateKeySecret:
                name: git-cred
                key: privateKey
      container:
        image: dkreg.kube-system:5000/alp.task:1.0.0-cicd
        command: [sh, -c]
        args: ["ls -al"]
        workingDir: /workdir/goweb
      outputs:
        artifacts:
          - name: git-repo
            path: /workdir/goweb

    - name: shellcheck
      inputs:
        artifacts:
          - name: git-repo
            path: /workdir/goweb
      container:
        image: dkreg.kube-system:5000/alp.shellcheck:1.0.0-cicd
        securityContext:
          privileged: true
        command: [sh, -c]
        args: ["task lint:shellcheck"]
        workingDir: /workdir/goweb

    - name: hadolint
      inputs:
        artifacts:
          - name: git-repo
            path: /workdir/goweb
      container:
        image: dkreg.kube-system:5000/alp.hadolint:1.0.0-cicd
        securityContext:
          privileged: true
        command: [sh, -c]
        args: ["task lint:hadolint"]
        workingDir: /workdir/goweb

    - name: compile
      inputs:
        artifacts:
          - name: git-repo
            path: /workdir/goweb
      container:
        image: dkreg.kube-system:5000/alp.golang:1.0.0-cicd
        securityContext:
          privileged: true
        command: [sh, -c]
        args: ["task compile"]
        workingDir: /workdir/goweb
      outputs:
        artifacts:
          - name: compile-output
            path: /workdir/goweb

    - name: test
      inputs:
        artifacts:
          - name: compile-output
            path: /workdir/goweb
      retryStrategy:
        limit: "3"
      container:
        image: dkreg.kube-system:5000/alp.task:1.0.0-cicd
        command: [sh, -c]
        args: ["task run; sleep 2; task test"]
        workingDir: /workdir/goweb

    - name: build
      inputs:
        artifacts:
          - name: compile-output
            path: /workdir/goweb
      container:
        image: dkreg.kube-system:5000/alp.podman:1.0.0-cicd
        securityContext:
          privileged: true
        command: [sh, -c]
        args: ["task build"]
        workingDir: /workdir/goweb

    - name: deploy
      inputs:
        artifacts:
          - name: compile-output
            path: /workdir/goweb
      container:
        image: dkreg.kube-system:5000/alp.kubectl:1.0.0-cicd
        securityContext:
          privileged: true
        command: [sh, -c]
        args: ["task deploy"]
        workingDir: /workdir/goweb
