# https://github.com/kubernetes/examples/blob/master/staging/storage/redis/README.md
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: s3-system
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis # has to match .spec.template.metadata.labels
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: redis # has to match .spec.selector.matchLabels
    spec:
      hostname: redis
      containers:
        - name: redis
          image: quay.io/flysangel/library/redis
          imagePullPolicy: Always # Always, Nerver, IfNotPresent
          resources:
            requests:
              cpu: "0.5"
              memory: "256Mi"
            limits:
              cpu: "2"
              memory: "2048Mi"
          volumeMounts:
            - name: redis
              mountPath: /data
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis
      restartPolicy: Always
