pipeline {
    agent {
        kubernetes {
            inheritFrom 'mycicd'
            yamlFile 'cicd-pod.yaml'
            defaultContainer 'p1'
        }
    }
    stages {
        stage ('Lint') {
            failFast true
            parallel {
                stage('Shellcheck') {
                    steps {
                        container('s1') {
                            sh 'task lint:shellcheck'
                        }
                    }
                }
                stage('hadolint') {
                    steps {
                        container('h1') {
                            sh 'task lint:hadolint'
                        }
                    }
                }
            }
        }         
        stage ('Compile') {
            steps {
                container('g1') {
                    sh 'task compile'
                }
            }
        }
        stage ('Test') {
            steps {
                sh 'task run'
                retry(3) {
                    sleep 2
                    sh 'task test'
                }
            }
        }
        stage ('Build') {
            steps {
                sh 'task build'
            }
        }
        stage ('Deploy') {
            input {
                message "請確認是否部署至 K1"
                parameters {
                    string(name: "NS", defaultValue: "default", description: "請輸入要部署至哪個 namespace")
                }
                ok "Yes"
            }
            steps {
                container('k1') {
                    sh 'task deploy NAMESPACE=$NS'
                }
            }
        }
    }
}