apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goweb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://bigred@kadm.kube-system:22100/home/bigred/devops/goweb
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # Sync policy
  syncPolicy:
    automated:
      selfHeal: true