apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-xadm
  labels:
    app: kube-xadm
  #annotations:
  #  metallb.universe.tf/loadBalancerIPs: 192.168.1.100
spec:
  selector:
    app: kube-xadm
  ports:
    - name: ssh
      port: 22102
      targetPort: 22
      protocol: TCP
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
