apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: kube-xadm
  labels:
    app: kube-xadm
spec:
  selector:
    matchLabels:
      app: kube-xadm # has to match .spec.template.metadata.labels
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: kube-xadm # has to match .spec.selector.matchLabels
    spec:
      nodeSelector:
        node-role.kubernetes.io/xadm: ""
      tolerations:
        - effect: NoSchedule
          operator: Exists
      serviceAccountName: kube-kadm
      hostname: kube-xadm
      containers:
        - name: kube-xadm
          image: quay.io/flysangel/image:x.adm-v1.0.0
          imagePullPolicy: Always # Always, Nerver, IfNotPresent
          # run podman
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "1"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "4096Mi"
          ports:
            # ssh
            - hostPort: 22102
              containerPort: 22
              protocol: TCP
          volumeMounts:
            - name: wulin
              mountPath: /home/bigred/wulin
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: wulin
          hostPath:
            path: /var/tmp/wulin
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
      restartPolicy: Always
