version: "3"

set: [errexit, nounset, pipefail]

tasks:
  install:
    desc: Install Argo CLI
    silent: true
    cmds:
      - bash "{{.ROOT_DIR}}/tools/argo/install.sh"

  uninstall:
    desc: Uninstall Argo CLI
    silent: true
    cmds:
      - bash "{{.ROOT_DIR}}/tools/uninstall.sh" argo
