version: "3"

tasks:
  default:
    cmds:
      - task -l
    silent: true

  lint:shellcheck:
    desc: Lint bash script
    cmds:
      - shellcheck src/web/cgi/*.sh

  lint:hadolint:
    desc: Lint Dockerfile
    cmds:
      - hadolint Dockerfile

  lint:kube-linter:
    desc: Lint kubernetes yaml
    cmds:
      - kube-linter lint k8s/*

  compile:
    desc: Compile the code into an executable
    cmds:
      - go mod tidy
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -buildvcs=false -o goweb ./src

  run:
    desc: Run goweb
    cmds:
      - mkdir -p /opt/www && cp -r src/web/* /opt/www/
      - nohup bash -c "./goweb 2>&1 &"

  test:
    desc: Test goweb
    cmds:
      - ./src/test/test.sh

  login:
    desc: Log in to private repository
    cmds:
      - sudo podman login --tls-verify=false -u bigred -p bigred 172.22.1.11:5000

  logout:
    desc: Logout of a container registry
    cmds:
      - sudo podman logout 172.22.1.11:5000 &>/dev/null

  build:
    desc: Build goweb image, and push to private repository
    cmds:
      - task: login
      - sudo podman build --tls-verify=false -t 172.22.1.11:5000/alp.goweb:1.0 .
      - sudo podman push --tls-verify=false 172.22.1.11:5000/alp.goweb:1.0
      - task: logout

  deploy:
    desc: Deploy to kubernetes cluster
    cmds:
      - kubectl delete -f k8s/ --ignore-not-found -n {{ default "default" .NAMESPACE}}
      - kubectl apply -f k8s/ -n {{ default "default" .NAMESPACE}}
