apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
# mc config host add mios http://miniosnsd.kube-system:9000 minio minio123
# mc mb mios/argo-workflows
# kubectl -n argo create secret generic mios-cred --from-literal=accesskey=minio --from-literal=secretkey=minio123
# archiveLogs will archive the main container logs as an artifact
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: argo-workflows
      endpoint: miniosnsd.kube-system:9000
      insecure: true
      accessKeySecret:
        name: mios-cred
        key: accesskey
      secretKeySecret:
        name: mios-cred
        key: secretkey