apiVersion: v1
kind: Pod
metadata:
  labels:
    app: fbs-minio
  name: fbs-minio
spec:
  containers:
  - image: 172.22.1.11:5000/alp.fbs:24.01
    name: fbs-s3fs
    lifecycle:
      postStart:
        exec:
          command:
            - /bin/bash
            - -c
            - |
              echo minio:minio123 > /tmp/.passwd-s3fs; chmod 600 /tmp/.passwd-s3fs;
              s3fs fbs /srv -o passwd_file=/tmp/.passwd-s3fs -o url=http://svc-mios.default:9000 -o use_path_request_style -o dbglevel=info -f -o curldbg &>/dev/null &
    ports:
    - containerPort: 4000
      hostPort: 4000
    securityContext:
      privileged: true
