kind: Service
apiVersion: v1
metadata:
  name: miniosnsd
  namespace: kube-system
  annotations:
    metallb.universe.tf/address-pool: mlb-pool
spec:
  allocateLoadBalancerNodePorts: false
  type: LoadBalancer
  loadBalancerIP: 172.22.1.150
  selector:
    app: miniosnsd
  ports:
  - name: mclient
    protocol: TCP
    port: 9000
    targetPort: 9000
  - name: mconsole
    protocol: TCP
    port: 9001
    targetPort: 9001
---
apiVersion: v1
kind: Pod
metadata:
  name: miniosnsd
  namespace: kube-system
  labels:
    app: miniosnsd
spec:
  hostname: minioserver
  volumes:
  - name: miniodata
    hostPath:
      path: /opt/miniosnsd
  containers:
  - name: minioserver
    image: minio/minio
    volumeMounts:
    - name: miniodata
      mountPath: /disk
    args:
    - server
    - --console-address
    - :9001
    - /disk
    env:
    - name: MINIO_ACCESS_KEY
      value: "minio"
    - name: MINIO_SECRET_KEY
      value: "minio123"
    ports:
    - containerPort: 9000
      name: mclient
      protocol: TCP
    - containerPort: 9001
      name: mconsole
      protocol: TCP 
