apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-fbs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dep-fbs
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50

