apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-fbs
  labels:
    app: dep-fbs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dep-fbs
  template:
    metadata:
      labels:
        app: dep-fbs
    spec:
      containers:
      - name: mygoweb
        image: quay.io/cloudwalker/alp.fbs:24.1
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: 70m
        volumeMounts:
        - name: fbs-storage
          mountPath: "/srv"
      volumes:
        - name: fbs-storage
          hostPath:
            path: /opt/fbs
