apiVersion: v1
kind: Service
metadata:
  name: svc-fbs
spec:
  type: ClusterIP
  externalIPs:
  - 192.168.61.4   
  selector:
    app: dep-fbs    
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
