apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-kadm
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-kadm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kube-kadm
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-xadm
  name: kube-xadm
  namespace: kube-system
spec:
  allocateLoadBalancerNodePorts: false
  ports:
  - name: ssh
    port: 22102
    protocol: TCP
    targetPort: 22
  selector:
    app: kube-xadm
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-xadm
  name: kube-xadm
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-xadm
  template:
    metadata:
      labels:
        app: kube-xadm
    spec:
      containers:
      - image: quay.io/flysangel/image:x.adm-v1.0.0
        imagePullPolicy: Always
        name: kube-xadm
        ports:
        - containerPort: 22
          hostPort: 22102
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4096Mi
          requests:
            cpu: "1"
            memory: 512Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /home/bigred/wulin
          name: wulin
        - mountPath: /dev/shm
          name: dshm
      hostname: kube-xadm
      nodeSelector:
        node-role.kubernetes.io/xadm: ""
      restartPolicy: Always
      serviceAccountName: kube-kadm
      tolerations:
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /var/tmp/wulin
        name: wulin
      - emptyDir:
          medium: Memory
          sizeLimit: 2Gi
        name: dshm
