kind: Deployment
apiVersion: apps/v1
metadata:
  name: c1-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c1
  template:
    metadata:
      name: c1
      labels:
        app: c1
    spec:
      containers:
        - name: c1
          image: dkreg.kube-system:5000/alp.cgi:latest
          imagePullPolicy: Always
