spec:
  serviceAccountName: cicd-admin
  containers:
  - name: p1
    image: dkreg.kube-system:5000/alp.podman:1.0.0-cicd
    securityContext:
      privileged: true
  - name: k1
    image: dkreg.kube-system:5000/alp.kubectl:1.0.0-cicd
    securityContext:
      privileged: true
