kind: Service
apiVersion: v1
metadata:
  name: svc-mysqld
  namespace: ndb
  annotations:
    metallb.universe.tf/address-pool: mlb-pool
spec:
  type: LoadBalancer
  loadBalancerIP: 172.22.1.148
  allocateLoadBalancerNodePorts: false
  selector:
    ndb-node-type: mysqld
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
