apiVersion: v1
kind: Service
metadata:
  labels:
    ndb-resource-type: mgmd-service
    app: ndb
  name: ndb-mgmd
  namespace: ndb
spec:
  ports:
  - name: mgmd-service-port
    port: 1186
    protocol: TCP
    targetPort: 1186
  selector:
    ndb-node-type: mgmd
    app: ndb
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    ndb-resource-type: mgmd-statefulset
    app: ndb
  name: ndb-mgmd
  namespace: ndb
spec:
  replicas: 1
  selector:
    matchLabels:
      ndb-node-type: mgmd
      app: ndb
  serviceName: ndb-mgmd
  template:
    metadata:
      labels:
        ndb-node-type: mgmd
        app: ndb
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  ndb-node-type: mysqld
              topologyKey: kubernetes.io/hostname
            weight: 5
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  ndb-node-type: ndbmtd
              topologyKey: kubernetes.io/hostname
            weight: 25
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  ndb-node-type: mgmd
              topologyKey: kubernetes.io/hostname
            weight: 50
      containers:
      - command:
        - /bin/bash
        - -ecx
        - /usr/sbin/ndb_mgmd -f /var/lib/ndb/config/config.ini --initial --nodaemon
        image: container-registry.oracle.com/mysql/community-cluster:8.1.0
        imagePullPolicy: IfNotPresent
        name: mgmd-container
        ports:
        - containerPort: 1186
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 1186
          timeoutSeconds: 1
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/ndb/data
          name: mgmd-data-vol
        - mountPath: /var/lib/ndb/config
          name: mgmd-config-volume
        - mountPath: /var/lib/ndb/run
          name: ndb-work-dir-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: ndb-work-dir-vol
      - emptyDir: {}
        name: mgmd-data-vol
      - configMap:
          defaultMode: 420
          items:
          - key: config.ini
            path: config.ini
          name: ndb-config
        name: mgmd-config-volume
