apiVersion: v1
kind: Service
metadata:
  labels:
    ndb-resource-type: mysqld-service
    app: ndb
  name: ndb-mysqld
  namespace: ndb
spec:
  ports:
  - name: mysqld-service-port
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    ndb-node-type: mysqld
    app: ndb
  type: ClusterIP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    ndb-resource-type: mysqld-statefulset
    app: ndb
  name: ndb-mysqld
  namespace: ndb
spec:
  replicas: 2
  selector:
    matchLabels:
      ndb-node-type: mysqld
      app: ndb
  serviceName: ndb-mysqld
  template:
    metadata:
      labels:
        ndb-node-type: mysqld
        app: ndb
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  ndb-node-type: mgmd
              topologyKey: kubernetes.io/hostname
            weight: 5
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  ndb-node-type: ndbmtd
              topologyKey: kubernetes.io/hostname
            weight: 25
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  ndb-node-type: mysqld
              topologyKey: kubernetes.io/hostname
            weight: 50
      containers:
      - image: container-registry.oracle.com/mysql/community-cluster:8.1.0   
        imagePullPolicy: IfNotPresent
        name: mysqld-container
        args: [ "mysqld", "--ndbcluster", "--ndb-connectstring=ndb-mgmd-0.ndb-mgmd.ndb.svc:1186", "--user=mysql", "--datadir=/var/lib/ndb/data" ]
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: ndb-mysqld-root-password
        ports:
        - containerPort: 3306
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/ndb/run
          name: ndb-work-dir-vol
        - mountPath: /var/lib/ndb/data
          name: mysqld-data-vol
        - mountPath: /docker-entrypoint-initdb.d/
          name: mysqld-init-scripts-vol
      dnsPolicy: ClusterFirst
      volumes:
      - emptyDir: {}
        name: ndb-work-dir-vol
      - emptyDir: {}
        name: mysqld-data-vol
      - name: mysqld-init-scripts-vol
        projected:
          defaultMode: 420
          sources:     
          - configMap:
              items:
              - key: users.sql
                path: users.sql           
              name: mysql-user
