apiVersion: v1
kind: Service
metadata:
  labels:
    ndb-resource-type: ndbmtd-service
    app: ndb
  name: ndb-ndbmtd
  namespace: ndb
spec:
  ports:
  - name: ndbmtd-service-port
    port: 1186
    protocol: TCP
    targetPort: 1186
  selector:
    ndb-node-type: ndbmtd
    app: ndb
  type: ClusterIP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    ndb-resource-type: ndbmtd-statefulset
    app: ndb
  name: ndb-ndbmtd
  namespace: ndb
spec:
  replicas: 2
  selector:
    matchLabels:
      ndb-node-type: ndbmtd
      app: ndb
  serviceName: ndb-ndbmtd
  template:
    metadata:
      labels:
        ndb-node-type: ndbmtd
        app: ndb
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  ndb-node-type: mgmd
              topologyKey: kubernetes.io/hostname
            weight: 5
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  ndb-node-type: mysqld
              topologyKey: kubernetes.io/hostname
            weight: 25
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  ndb-node-type: ndbmtd
              topologyKey: kubernetes.io/hostname
            weight: 50
      containers:
      - command:
        - /bin/bash
        - -ecx
        - /usr/sbin/ndbmtd -c ndb-mgmd-0.ndb-mgmd.ndb.svc:1186 --foreground
        image: container-registry.oracle.com/mysql/community-cluster:8.1.0   
        imagePullPolicy: IfNotPresent
        name: ndbmtd-container
        ports:
        - containerPort: 1186
          protocol: TCP
        resources:
          requests:
            memory: 529518864
        volumeMounts:
        - mountPath: /var/lib/ndb/data
          name: ndbmtd-data-vol
        - mountPath: /var/lib/ndb/run
          name: ndb-work-dir-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: ndb-work-dir-vol
      - emptyDir: {}
        name: ndbmtd-data-vol
