pipeline {
    agent {
        kubernetes {
            inheritFrom 'mycicd'
            yamlFile 'cicd-pod.yaml'
            defaultContainer 'p1'
        }
    }
    stages {
        stage ('Compile') {
            steps {
                container('g1') {
                    sh 'task compile'
                }
            }
        }
        stage ('Test') {
            steps {
                sh 'task run'
                retry(3) {
                    sleep 2
                    sh 'task test'
                }
            }
        }
        stage ('Build') {
            steps {
                sh 'task build'
            }
        }
        stage ('Deploy') {
            steps {
                container('k1') {
                    sh 'task deploy'
                }
            }
        }
    }
}