apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: mariadb
spec:
  storageClassName: juicefs-minio
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 10Gi
