kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: s3-system
  name: redis
spec:
  storageClassName: local-path
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
      