apiVersion: v1
kind: Namespace
metadata:
  name: s3-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: s3-system
spec:
  clusterIP: None
  ports:
  - port: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: s3-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: s3-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: quay.io/flysangel/library/redis
        imagePullPolicy: Always
        name: redis
        resources:
          limits:
            cpu: "2"
            memory: 2048Mi
          requests:
            cpu: "0.5"
            memory: 256Mi
        volumeMounts:
        - mountPath: /data
          name: redis
      hostname: redis
      restartPolicy: Always
      volumes:
      - name: redis
        persistentVolumeClaim:
          claimName: redis
