apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb # has to match .spec.template.metadata.labels
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mariadb # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: mariadb
          image: quay.io/flysangel/library/mariadb
          imagePullPolicy: IfNotPresent
          args:
            [
              "--character-set-server=utf8mb4",
              "--collation-server=utf8mb4_general_ci",
            ]
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: root
            - name: MARIADB_DATABASE
              value: dbtest
            - name: MARIADB_USER
              value: mariadb
            - name: MARIADB_PASSWORD
              value: mymariadbmariadb
            - name: TZ
              value: Asia/Taipei
          volumeMounts:
            - name: mariadb
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb
          persistentVolumeClaim:
            claimName: mariadb
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: mariadb
spec:
  storageClassName: juicefs-minio
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 10Gi
