apiVersion: v1
kind: Pod
metadata:
  namespace: s3-system
  name: minio-mg
  labels:
    app: minio-mg # service selector
spec:
  containers:
    - name: minio-mg
      image: quay.io/flysangel/image:alpine.s3cli-v1.0.0
  restartPolicy: Always
