apiVersion: v1
kind: Namespace
metadata:
  name: s3-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
  namespace: s3-system
spec:
  allocateLoadBalancerNodePorts: false
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: ui
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: minio
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio-mgr
  name: minio-mgr
  namespace: s3-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-mgr
  template:
    metadata:
      labels:
        app: minio-mgr
    spec:
      containers:
      - image: quay.io/flysangel/image:alpine.s3cli-v1.0.0
        imagePullPolicy: Always
        name: minio-mgr
        resources:
          limits:
            cpu: 512m
            memory: 512Mi
          requests:
            cpu: 256m
            memory: 256Mi
      hostname: minio-mgr
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: minio
  name: minio
  namespace: s3-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minio
  serviceName: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - args:
        - server
        - http://minio-{0...1}.minio.s3-system.svc.cluster.local/data{0...1}
        env:
        - name: MINIO_ACCESS_KEY
          value: minio
        - name: MINIO_SECRET_KEY
          value: minio123
        image: quay.io/flysangel/minio/minio
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /minio/health/live
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: minio
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: "2"
            memory: 2048Mi
          requests:
            cpu: "0.5"
            memory: 256Mi
        volumeMounts:
        - mountPath: /data0
          name: minio-data0
        - mountPath: /data1
          name: minio-data1
  volumeClaimTemplates:
  - metadata:
      name: minio-data0
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: local-path
  - metadata:
      name: minio-data1
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: local-path
