apiVersion: v1
kind: Service
metadata:
  namespace: s3-system
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: ui
      port: 9001
      targetPort: 9001
      protocol: TCP
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
