apiVersion: v1
kind: Namespace
metadata:
  name: s3-system
---
apiVersion: v1
kind: Service
metadata:
  namespace: s3-system
  name: minio
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: ui
      port: 9001
      targetPort: 9001
      protocol: TCP
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
---
# https://github.com/kubernetes/examples/tree/master/staging/storage/minio
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: s3-system
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio # has to match .spec.template.metadata.labels
  serviceName: minio
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: minio # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: minio
          image: quay.io/flysangel/minio/minio
          imagePullPolicy: Always # Always, Nerver, IfNotPresent
          resources:
            requests:
              cpu: "0.5"
              memory: "256Mi"
            limits:
              cpu: "2"
              memory: "2048Mi"
          args:
            # Change this according to No. of replicas, namespace and volumes
            - server
            - http://minio-{0...1}.minio.s3-system.svc.cluster.local/data{0...1}
          env:
            # MinIO access key and secret key
            - name: MINIO_ACCESS_KEY
              value: "minio"
            - name: MINIO_SECRET_KEY
              value: "minio123"
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: minio-data0
              mountPath: /data0
            - name: minio-data1
              mountPath: /data1
  volumeClaimTemplates:
    - metadata:
        name: minio-data0
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: minio-data1
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: s3-system
  name: minio-mgr
  labels:
    app: minio-mgr
spec:
  selector:
    matchLabels:
      app: minio-mgr # has to match .spec.template.metadata.labels
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: minio-mgr # has to match .spec.selector.matchLabels
    spec:
      hostname: minio-mgr
      containers:
        - name: minio-mgr
          image: quay.io/flysangel/image:alpine.s3cli-v1.0.0
          imagePullPolicy: Always # Always, Nerver, IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "256m"
            limits:
              memory: "512Mi"
              cpu: "512m"
