apiVersion: v1
kind: Pod
metadata:
  name: dtw1
  namespace: kube-system
  labels:
    app: hdp
spec:
  hostname: dtw1
  subdomain: hdp 
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 10.98.0.10
    searches:
      - hdp.kube-system.svc.k1.org
      - kube-system.svc.k1.org
      - svc.k1.org
  volumes:
  - name: dn
    hostPath:
      path: /var/dtw1-dn
  - name: hdpsys
    emptyDir: {}
  initContainers:
  - name: volume-permissions
    image: 172.22.1.11:5000/us.dt:24.01
    command: ["/bin/sh"]
    args: ["-c", "chmod -R 755 /home/bigred/dn && chown 1000:1000 /home/bigred/dn"]
    volumeMounts:
    - name: dn
      mountPath: /home/bigred/dn
  containers:
  - name: dtw1
    image: 172.22.1.11:5000/us.dt:24.01
    imagePullPolicy: Always
    tty: true 
    securityContext:
      privileged: true
    volumeMounts:
    - name: dn
      mountPath: /home/bigred/dn
    - name: hdpsys
      mountPath: /opt/dtp
      mountPropagation: Bidirectional
  - name: s3fs
    image: quay.io/cloudwalker/alp.s3fs
    imagePullPolicy: Always
    securityContext:
      privileged: true
    volumeMounts:
    - name: hdpsys
      mountPath: /s3
      mountPropagation: Bidirectional   
    env:
    - name: USER
      value: minio
    - name: PASSWORD
      value: minio123
    - name: URL
      value: http://miniosnsd.kube-system:9000
    - name: BUCKET
      value: dtp
    - name: EXTARG
      value: ""
      value: "-o uid=1000 -o gid=1000 -o umask=000"
    - name: DEBUG
      value: "-o dbglevel=info -o curldbg -f"
---
