apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins

resources:
  - mkdir-job.yaml
  - namespace.yaml
  - install.yaml
  - cicd-admin-sa.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: jenkins