apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: jenkins
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
---
apiVersion: v1
data:
  base.yaml: |
    dW5jbGFzc2lmaWVkOgogIGxvY2F0aW9uOgogICAgdXJsOiAiaHR0cDovLyR7SkVOS0lOU1
    9VUkw6LWRldm9wcy5qZW5raW5zfSIKYXBwZWFyYW5jZToKICBsb2NhbGU6CiAgICBzeXN0
    ZW1Mb2NhbGU6IGVuX1VTCiAgICBpZ25vcmVBY2NlcHRMYW5ndWFnZTogdHJ1ZQpqZW5raW
    5zOgogIGRpc2FibGVkQWRtaW5pc3RyYXRpdmVNb25pdG9yczoKICAgIC0gImplbmtpbnMu
    c2VjdXJpdHkuUXVldWVJdGVtQXV0aGVudGljYXRvck1vbml0b3IiCiAgICAtICJqZW5raW
    5zLmRpYWdub3N0aWNzLkNvbnRyb2xsZXJFeGVjdXRvcnNBZ2VudHMiCiAgbGFiZWxTdHJp
    bmc6ICJjb250cm9sbGVyIgogIHNlY3VyaXR5UmVhbG06CiAgICBsb2NhbDoKICAgICAgYW
    xsb3dzU2lnbnVwOiBmYWxzZQogICAgICB1c2VyczoKICAgICAgICAtIGlkOiAiJHtKRU5L
    SU5TX0FETUlOX0lEOi1qZW5raW5zfSIKICAgICAgICAgIHBhc3N3b3JkOiAiJHtKRU5LSU
    5TX0FETUlOX1BXOi1KZW5raW5zMTIzNDV9IgogIGF1dGhvcml6YXRpb25TdHJhdGVneToK
    ICAgIGdsb2JhbE1hdHJpeDoKICAgICAgcGVybWlzc2lvbnM6CiAgICAgICAgLSAiVVNFUj
    pPdmVyYWxsL0FkbWluaXN0ZXI6JHtKRU5LSU5TX0FETUlOX0lEOi1qZW5raW5zfSIKICAg
    ICAgICAtICJHUk9VUDpPdmVyYWxsL1JlYWQ6YXV0aGVudGljYXRlZCIKc2VjdXJpdHk6Ci
    AgZ2l0SG9zdEtleVZlcmlmaWNhdGlvbkNvbmZpZ3VyYXRpb246CiAgICBzc2hIb3N0S2V5
    VmVyaWZpY2F0aW9uU3RyYXRlZ3k6ICJub0hvc3RLZXlWZXJpZmljYXRpb25TdHJhdGVneS
    IKICBxdWV1ZUl0ZW1BdXRoZW50aWNhdG9yOgogICAgYXV0aGVudGljYXRvcnM6CiAgICAg
    IC0gZ2xvYmFsOgogICAgICAgICAgc3RyYXRlZ3k6IHRyaWdnZXJpbmdVc2Vyc0F1dGhvcm
    l6YXRpb25TdHJhdGVneQ==
  cloud.yaml: |
    amVua2luczoKICBjbG91ZHM6CiAgICAtIGt1YmVybmV0ZXM6CiAgICAgICAgbmFtZTogIm
    sxIgogICAgICAgIG5hbWVzcGFjZTogImplbmtpbnMiCiAgICAgICAgamVua2luc1VybDog
    Imh0dHA6Ly9kZXZvcHMuamVua2lucyIKICAgICAgICB0ZW1wbGF0ZXM6CiAgICAgICAgIC
    AtIG5hbWU6ICJteWNpY2QiCiAgICAgICAgICAgIGxhYmVsOiAibXljaWNkIgogICAgICAg
    ICAgICBjb250YWluZXJzOgogICAgICAgICAgICAgIC0gbmFtZTogImpubHAiCiAgICAgIC
    AgICAgICAgICBpbWFnZTogInF1YXkuaW8vZmx5c2FuZ2VsL2plbmtpbnMvaW5ib3VuZC1h
    Z2VudDozMjYxLnY5YzY3MGFfNDc0OGFfOS0yLWFscGluZS1qZGsyMSIKICAgICAgICAgIC
    AgICAgIGNvbW1hbmQ6ICIiCiAgICAgICAgICAgICAgICBhcmdzOiAiIgogICAgICAgICAg
    ICAgICAgd29ya2luZ0RpcjogIi9ob21lL2plbmtpbnMvYWdlbnQiCiAgICAgICAgICAgIH
    lhbWxNZXJnZVN0cmF0ZWd5OiAib3ZlcnJpZGUi
kind: Secret
metadata:
  labels:
    app: jenkins
  name: jenkins-casc
  namespace: jenkins
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: devops
  namespace: jenkins
spec:
  ports:
  - name: jenkins-http
    port: 80
    targetPort: 8080
  - name: jenkins-agent
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: jenkins
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - env:
        - name: LIMITS_MEMORY
          valueFrom:
            resourceFieldRef:
              divisor: 1Mi
              resource: limits.memory
        - name: JAVA_OPTS
          value: -Djenkins.install.runSetupWizard=false -Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Taipei
            -Dhudson.plugins.git.GitStatus.NOTIFY_COMMIT_ACCESS_CONTROL=disabled -Xmx$(LIMITS_MEMORY)m
            -XshowSettings:vm -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50
            -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85
        image: quay.io/grassknot/jenkins.jcasc:1.3.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 24
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
        name: jenkins
        ports:
        - containerPort: 8080
        - containerPort: 50000
        readinessProbe:
          failureThreshold: 24
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 0.5
            memory: 500Mi
        startupProbe:
          failureThreshold: 24
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /usr/jenkins_config/
          name: jenkins-config
        - mountPath: /var/jenkins_home
          name: jenkins-storage
      nodeSelector:
        node: jenkins
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: jenkins
      volumes:
      - name: jenkins-config
        secret:
          secretName: jenkins-casc
      - hostPath:
          path: /opt/jenkins
        name: jenkins-storage
