apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
- github.com/kubernetes-sigs/metrics-server/manifests/overlays/release?ref=v0.7.1

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --kubelet-insecure-tls
  target:
    kind: Deployment

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: metrics-server
