kind: Deployment
apiVersion: apps/v1
metadata:
  name: dep-derby
  labels:
    app: dep-derby
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dep-derby
  template:
    metadata:
      labels:
        app: dep-derby 
    spec:
      containers:
      - name: derbyapp
        image: 172.22.1.11:5000/alpine.derby
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8888  
